# Generated by Django 5.1.6 on 2025-02-26 02:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('centros_medicos', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmado', 'Confirmado'), ('cancelado', 'Cancelado')], max_length=20)),
                ('consultorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='centros_medicos.consultorio')),
            ],
        ),
    ]
