# Generated by Django 5.1.6 on 2025-02-26 02:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('centros_medicos', '0001_initial'),
        ('obras_sociales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='convenioobrasocial',
            name='obra_social',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='obras_sociales.obrasocial'),
        ),
        migrations.AddField(
            model_name='centromedico',
            name='obras_sociales',
            field=models.ManyToManyField(through='centros_medicos.ConvenioObraSocial', to='obras_sociales.obrasocial'),
        ),
        migrations.AddField(
            model_name='horarioatencion',
            name='consultorio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='centros_medicos.consultorio'),
        ),
        migrations.AddField(
            model_name='medicocentromedico',
            name='centro_medico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicos', to='centros_medicos.centromedico'),
        ),
        migrations.AddField(
            model_name='medicocentromedico',
            name='horarios',
            field=models.ManyToManyField(to='centros_medicos.horarioatencion'),
        ),
    ]
