# Generated by Django 5.1.6 on 2025-03-03 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InsumoMedico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('cantidad', models.PositiveIntegerField()),
                ('fecha_vencimiento', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='MaterialQuirurgico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('tipo', models.CharField(max_length=100)),
                ('stock', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unidad_medida', models.CharField(max_length=50)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('lote', models.CharField(blank=True, max_length=100)),
                ('proveedor', models.CharField(blank=True, max_length=200)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Material Quirúrgico',
                'verbose_name_plural': 'Materiales Quirúrgicos',
            },
        ),
        migrations.CreateModel(
            name='MedicamentoQuirurgico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('principio_activo', models.CharField(max_length=200)),
                ('concentracion', models.CharField(max_length=100)),
                ('presentacion', models.CharField(max_length=100)),
                ('via_administracion', models.CharField(max_length=100)),
                ('stock', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unidad_medida', models.CharField(max_length=50)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('lote', models.CharField(blank=True, max_length=100)),
                ('laboratorio', models.CharField(blank=True, max_length=200)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Medicamento Quirúrgico',
                'verbose_name_plural': 'Medicamentos Quirúrgicos',
            },
        ),
        migrations.CreateModel(
            name='UsoMedicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosis_aplicada', models.CharField(max_length=50)),
                ('fecha_aplicacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UsoMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_usada', models.IntegerField()),
                ('fecha_uso', models.DateTimeField(auto_now_add=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insumos_medicos.materialquirurgico')),
            ],
        ),
    ]
