# Generated by Django 5.1.6 on 2025-03-03 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('insumos_medicos', '0001_initial'),
        ('operaciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usomaterial',
            name='operacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operaciones.operacion'),
        ),
        migrations.AddField(
            model_name='usomedicamento',
            name='medicamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insumos_medicos.medicamentoquirurgico'),
        ),
        migrations.AddField(
            model_name='usomedicamento',
            name='operacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operaciones.operacion'),
        ),
    ]
