# Generated by Django 5.1.6 on 2025-02-26 02:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('centros_medicos', '0003_initial'),
        ('operaciones', '0001_initial'),
        ('pacientes', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipoquirurgico',
            name='cirujanos_asistentes',
            field=models.ManyToManyField(related_name='asistencias_quirurgicas', to='usuarios.medico'),
        ),
        migrations.AddField(
            model_name='equipoquirurgico',
            name='enfermeros',
            field=models.ManyToManyField(related_name='operaciones', to='operaciones.enfermero'),
        ),
        migrations.AddField(
            model_name='operacion',
            name='anestesiologo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operaciones_como_anestesiologo', to='usuarios.medico'),
        ),
        migrations.AddField(
            model_name='operacion',
            name='centro_medico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='centros_medicos.centromedico'),
        ),
        migrations.AddField(
            model_name='operacion',
            name='cirujano_principal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operaciones_como_cirujano', to='usuarios.medico'),
        ),
        migrations.AddField(
            model_name='operacion',
            name='instrumentador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operaciones_como_instrumentador', to='usuarios.medico'),
        ),
        migrations.AddField(
            model_name='operacion',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operaciones', to='pacientes.paciente'),
        ),
        migrations.AddField(
            model_name='operacion',
            name='quirofano',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='centros_medicos.quirofano'),
        ),
        migrations.AddField(
            model_name='equipoquirurgico',
            name='operacion',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='equipo', to='operaciones.operacion'),
        ),
        migrations.AddField(
            model_name='prequirurgicopaciente',
            name='estudio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operaciones.estudioprequirurgico'),
        ),
        migrations.AddField(
            model_name='prequirurgicopaciente',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estudios_prequirurgicos', to='pacientes.paciente'),
        ),
        migrations.AddField(
            model_name='operacion',
            name='procedimiento_especifico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='operaciones.procedimientoespecifico'),
        ),
        migrations.AddField(
            model_name='protocolo',
            name='medico_responsable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usuarios.medico'),
        ),
        migrations.AddField(
            model_name='protocolo',
            name='operacion',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='protocolo', to='operaciones.operacion'),
        ),
        migrations.AddField(
            model_name='procedimientoespecifico',
            name='tipo_cirugia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operaciones.tipocirugia'),
        ),
        migrations.AddField(
            model_name='plantillaprotocolo',
            name='tipo_cirugia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plantillas', to='operaciones.tipocirugia'),
        ),
        migrations.AddField(
            model_name='operacion',
            name='tipo_cirugia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='operaciones.tipocirugia'),
        ),
        migrations.AddField(
            model_name='estudioprequirurgico',
            name='tipo_cirugia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estudios_requeridos', to='operaciones.tipocirugia'),
        ),
    ]
