# Generated by Django 5.1.6 on 2025-02-26 02:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('obras_sociales', '0001_initial'),
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='autorizacion',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='autorizaciones_obra_social', to='pacientes.paciente'),
        ),
        migrations.AddField(
            model_name='autorizacion',
            name='cobertura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='obras_sociales.cobertura'),
        ),
        migrations.AddField(
            model_name='plan',
            name='obra_social',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planes', to='obras_sociales.obrasocial'),
        ),
        migrations.AddField(
            model_name='cobertura',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coberturas', to='obras_sociales.plan'),
        ),
        migrations.AlterUniqueTogether(
            name='plan',
            unique_together={('obra_social', 'codigo')},
        ),
        migrations.AlterUniqueTogether(
            name='cobertura',
            unique_together={('plan', 'procedimiento')},
        ),
    ]
