# Generated by Django 5.1.6 on 2025-03-03 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consultas', '0002_initial'),
        ('informes', '0001_initial'),
        ('insumos_medicos', '0002_initial'),
        ('operaciones', '0001_initial'),
        ('pacientes', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='firmadigital',
            name='medico',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='usuarios.medico'),
        ),
        migrations.AddField(
            model_name='firmainforme',
            name='firma_digital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='informes.firmadigital'),
        ),
        migrations.AddField(
            model_name='firmainforme',
            name='medico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usuarios.medico'),
        ),
        migrations.AddField(
            model_name='firmaprotocolo',
            name='firma_digital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='informes.firmadigital'),
        ),
        migrations.AddField(
            model_name='firmaprotocolo',
            name='medico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usuarios.medico'),
        ),
        migrations.AddField(
            model_name='informe',
            name='consulta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='consultas.consulta'),
        ),
        migrations.AddField(
            model_name='informe',
            name='medico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.medico'),
        ),
        migrations.AddField(
            model_name='informe',
            name='operacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='operaciones.operacion'),
        ),
        migrations.AddField(
            model_name='informe',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pacientes.paciente'),
        ),
        migrations.AddField(
            model_name='firmainforme',
            name='informe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='firmas', to='informes.informe'),
        ),
        migrations.AddField(
            model_name='materialprocedimiento',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='insumos_medicos.materialquirurgico'),
        ),
        migrations.AddField(
            model_name='medicamentoprocedimiento',
            name='medicamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='insumos_medicos.medicamentoquirurgico'),
        ),
        migrations.AddField(
            model_name='plantillainforme',
            name='creado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.medico'),
        ),
        migrations.AddField(
            model_name='informe',
            name='plantilla',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='informes.plantillainforme'),
        ),
        migrations.AddField(
            model_name='protocoloprocedimiento',
            name='anestesiologo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='procedimientos_anestesia', to='usuarios.medico'),
        ),
        migrations.AddField(
            model_name='protocoloprocedimiento',
            name='informe',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='protocolo_procedimiento', to='informes.informe'),
        ),
        migrations.AddField(
            model_name='medicamentoprocedimiento',
            name='protocolo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicamentos', to='informes.protocoloprocedimiento'),
        ),
        migrations.AddField(
            model_name='materialprocedimiento',
            name='protocolo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materiales', to='informes.protocoloprocedimiento'),
        ),
        migrations.AddField(
            model_name='firmaprotocolo',
            name='protocolo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='firmas', to='informes.protocoloprocedimiento'),
        ),
        migrations.AddField(
            model_name='componenteprocedimiento',
            name='protocolo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='componentes', to='informes.protocoloprocedimiento'),
        ),
        migrations.AddField(
            model_name='seguimientopostprocedimiento',
            name='medico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usuarios.medico'),
        ),
        migrations.AddField(
            model_name='seguimientopostprocedimiento',
            name='protocolo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguimientos', to='informes.protocoloprocedimiento'),
        ),
        migrations.AddField(
            model_name='variablepersonalizada',
            name='medico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.medico'),
        ),
        migrations.AddField(
            model_name='versioninforme',
            name='informe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versiones', to='informes.informe'),
        ),
        migrations.AddField(
            model_name='versioninforme',
            name='medico_modificacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usuarios.medico'),
        ),
        migrations.AddField(
            model_name='firmainforme',
            name='version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='informes.versioninforme'),
        ),
        migrations.AlterUniqueTogether(
            name='plantillainforme',
            unique_together={('nombre', 'tipo')},
        ),
        migrations.AlterUniqueTogether(
            name='firmaprotocolo',
            unique_together={('protocolo', 'medico', 'rol')},
        ),
        migrations.AlterUniqueTogether(
            name='variablepersonalizada',
            unique_together={('medico', 'nombre')},
        ),
        migrations.AlterUniqueTogether(
            name='versioninforme',
            unique_together={('informe', 'version')},
        ),
        migrations.AlterUniqueTogether(
            name='firmainforme',
            unique_together={('informe', 'medico', 'rol')},
        ),
    ]
